# .spacelift/config.yml
version: "2"

stack_defaults:
  # Override the default runner image globally
  #runner_image: public.ecr.aws/spacelift/runner-ansible:2.15.8

stacks:
  # Optionally override per-stack by slug
  az-ansible:
    runner_image: public.ecr.aws/spacelift/runner-ansible:11.4-azure

  before_init:
    - apt-get update && apt-get install -y curl
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - uv pip install -r requirements.txt