---
- name: Ping all Linux systems
  hosts: os_linux
  become: yes
  vars_files:
    - vars/connection-linux.yml

  tasks:
  - name: Ping all Linux systems
    ping:

  - name: Timezone - London UK
    ansible.builtin.timezone:
      name: 'Europe/London'