---
- name: Ping all Linux systems
  hosts: os_linux
  become: yes
  vars_files:
    - vars/connection-linux.yml

  tasks:
  - name: "Linux: Ping"
    ping:

  - name: "Linux: Update Timezone"
    ansible.builtin.timezone:
      name: 'Europe/London'