---
- name: Store Public DNS of VM as a variable
  set_fact:
    vm_public_dns: "{{ hostvars[inventory_hostname].public_dns_hostnames[0] }}"

- name: Use the stored public DNS in another task
  debug:
    msg: "The stored public DNS is: {{ vm_public_dns }}"

- name: Check if certificate exists by friendly name with wildcard
  win_shell: |
    $cert = Get-ChildItem -Path Cert:\LocalMachine\My | Where-Object { $_.FriendlyName -like 'azure-cert*' }
    if ($cert) { exit 0 } else { exit 1 }
  register: cert_check
  ignore_errors: true

- name: Debug certificate check
  debug:
    msg: "Certificate check result: {{ cert_check.rc }}"
  
- name: Create certificate if not present
  win_command: |
    wacs.exe --accepttos --host "{{ vm_public_dns }}" --source manual --friendlyname "azure-cert"
  when: cert_check.rc != 0
  register: cert_creation

- name: Ensure certificate was created
  assert:
    that:
      - cert_creation.rc == 0
  when: cert_check.rc != 0

- name: Set certificate thumbprint for RDP listener
  win_shell: |
    $tsgs = gwmi -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -Filter "TerminalName='RDP-tcp'"
    $azureCert = gci -path cert:/LocalMachine/My | Where-Object { $_.FriendlyName -like "*azure-cert*" }
    $thumb = $azureCert.Thumbprint
    swmi -path $tsgs.__path -argument @{SSLCertificateSHA1Hash="$thumb"}
    Restart-Service -Name TermService -Force
  when: cert_check.rc != 0

- name: Add Firefox syspin to Run key
  win_regedit:
    path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
    name: 'PinFirefoxSyspin'
    data: 'syspin "C:\Program Files\Mozilla Firefox\firefox.exe" 51201'
    type: string
    state: present

- name: Find Edge uninstaller
  win_find:
    paths: 'C:\Program Files (x86)\Microsoft\Edge\Application'
    patterns: 'setup.exe'
    recurse: yes
  register: edge_installer
  no_log: true
  tags:
    - uninstall_msedge

- name: Uninstall Microsoft Edge via shell
  win_shell: >
    "{{ item.path }}" --uninstall --system-level --verbose-logging --force-uninstall
  loop: "{{ edge_installer.files }}"
  when: edge_installer.matched > 0
  args:
    executable: cmd
  changed_when: edge_installer.matched > 0
  failed_when: false
  tags:
    - uninstall_msedge

- name: Registry - Configuration updates
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data | default(omit) }}"
    type: "{{ item.type | default('dword') }}"
    state: "{{ item.state | default('present') }}"
  loop:
    - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa', name: 'LimitBlankPasswordUse', data: 0 }
    - { path: 'HKLM:\Software\Policies\Microsoft\WindowsStore', name: 'DisableStoreApps', data: 1 }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', name: 'EnableAutoTray', data: 0 }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'Hidden' }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'HideFileExt', data: 0 }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent', name: 'DisableWindowsConsumerFeatures', data: 1 }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent', name: 'DisableSoftLanding', data: 1 }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent', name: 'DisableThirdPartySuggestions', data: 1 }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent', name: 'DisableWindowsSpotlightFeatures', data: 1 }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection', name: 'AllowTelemetry', data: 0 }
    - { path: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'ShowTaskViewButton', data: 0 }
    - { path: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People', name: 'PeopleBand', data: 0 }
    - { path: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', name: 'EnableAutoTray', data: 0 }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Search', name: 'SearchboxTaskbarMode', data: 0 }
    - { path: 'HKCU:\Software\Policies\Microsoft\Windows\Explorer', name: 'DisableNotificationCenter', data: 1 }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'HideSCAVolume', data: 1 }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'NoTaskGrouping', data: 1 }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel\', name: 'AllItemsIconView', data: 1 }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel\', name: 'StartupPage', data: 1 }
    - { path: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'NavPaneShowAllFolders', data: 1 }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search', name: 'AllowCortana', data: 0 }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'ShowCortanaButton', data: 0 }
    - { path: 'HKLM:\Software\Policies\Microsoft\Windows\Explorer', name: 'HideRecentlyAddedApps', data: 1 }
    - { path: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search', name: 'BingSearchEnabled', data: 0 }
    - { path: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search', name: 'CortanaConsent', data: 0 }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search', name: 'DisableWebSearch', data: 1 }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds', name: 'EnableFeeds', data: 0 }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'HideSCAMeetNow', data: 1 }
    - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\Network', name: 'NewNetworkWindowOff', data: 1 }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}', name: 'IsInstalled', data: 0 }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}', name: 'IsInstalled', data: 0 }
  tags:
    - registry
  register: registry_update
  notify: Reboot - Registry updated
