---
- name: Check if Firefox is default HTTP handler
  ansible.windows.win_shell: >
    powershell -NoProfile -Command "(Get-ItemProperty 'HKCU:\\Software\\Microsoft\\Windows\\Shell\\Associations\\UrlAssociations\\http\\UserChoice').ProgId"
  register: http_default
  changed_when: false
  failed_when: false

- name: Set Firefox as default browser
  ansible.windows.win_shell: setdefaultbrowser.exe HKLM Firefox-308046B0AF4A39CB
  when: "'Firefox' not in http_default.stdout"

- name: Create distribution directory for Firefox
  win_file:
    path: C:\Program Files\Mozilla Firefox\distribution
    state: directory

- name: Copy Firefox policies.json from repository
  win_copy:
    src: scripts/firefox/policies.json
    dest: C:\Program Files\Mozilla Firefox\distribution\policies.json

- name: Copy autoconfig.js from repository
  win_copy:
    src: scripts/firefox/autoconfig.js
    dest: C:\Program Files\Mozilla Firefox\defaults\pref\autoconfig.js

- name: Copy firefox.cfg from repository
  win_copy:
    src: scripts/firefox/firefox.cfg
    dest: C:\Program Files\Mozilla Firefox\firefox.cfg